{% set name = "pyusb" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d69ed64bff0e2102da11b3f49567256867853b861178689671a163d30865c298

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - libusb

test:
  imports:
    - usb

about:
  home: https://github.com/pyusb/pyusb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Easy access to the host machine's Universal Serial Bus system in Python.

  description: |
    PyUSB offers easy USB devices communication in Python.
    It should work without additional code in any environment with
    Python >= 2.4, ctypes and an pre-built usb backend library
    (currently, libusb 0.1.x, libusb 1.x, and OpenUSB).

extra:
  recipe-maintainers:
    - hmaarrfk
