{% set name = "pyusb" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e6de8ef79e164ced020d8131cd17d45a3cdeefb7afdaf41d7a2cbf2378828c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - libusb

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - usb
  commands:
    # The pip version can reported incorrectly if setuptools_scm isn't available
    # at build time
    # https://github.com/conda-forge/pyusb-feedstock/issues/3
    - pip list | grep -i {{ name }} | grep {{ version }}

about:
  home: https://github.com/pyusb/pyusb
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Easy access to the host machine's Universal Serial Bus system in Python.

  description: |
    PyUSB offers easy USB devices communication in Python.
    It should work without additional code in any environment with
    Python >= 2.4, ctypes and an pre-built usb backend library
    (currently, libusb 0.1.x, libusb 1.x, and OpenUSB).

extra:
  recipe-maintainers:
    - hmaarrfk
