travis:
  secure:
    BINSTAR_TOKEN: hOSNwiIjXb2KQeFjKsTQNuXHZhXYML7vZuJoMQCxecVXhkZKiD6MZJI1YElYtAbxiTJv3B9qHuWrLdl3/xcDzKlt3hg59yHkQ1bpjCjRSk918MqvIgBpAVMGfb3MfB8GH/Hvm/gySmti+JuewFtvZpTw8eqP4Z8iLgXG4eblbPC5rX4MYRQO5x/x69ci36UBM2LjrPfTSUf9rM8QTal2x8K6/tlsbHNWEd1ZMx2beTyC1Kl+FchI3QX7Tn9p+8uL3mjXFm+Kgv8Hjl8ruLq5eVqH1A1xq9f7pV9TkIcIGXJHqx1ce0Il3KWaYILnFWsBrQOgDRgIgF3u2x2ealBs754yL5ah/dLG8rG/K5+j+UwwQamrJZXlkCZ5W0uTx2AWgL+wBrLWjech/4x0ADQyIzzEfKiIo1Q9stwhBX1mygmII6re2RccdVaBPqUTYNoXnSQR/lW+KnPxQqHuUljqgnUfK2v52R9p0VQT3909SQZdzTGKSpUfwR6eXqYiDJ3CCYIZbCI75LqNXP6+bDs5jvSgV6sO2rdiqtU6UyBDDaMA2Ckmw4ezF4N8TELfBzdqRc/RcQXbP1sH0JIHg+qUM8aQpkx51SL2CEEJ1LNIDvj8Jmeq/GDmJSvI263M3QgIfcc0YwIt+MU4o4Az11AEyK1xvLrfJ4HfcD6cguFQuis=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
